version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=86000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_NAME=event-manager
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:
