version: '3.8'

services:
  app:
    build: .
    container_name: event_manager_app
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017/event-manager
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    container_name: event_manager_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    container_name: event_manager_redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
